### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by Brikwerk** [Brikwerk/nxbt#1]
This is an issue to track Windows support. 

Currently, it's not possible to access the L2CAP layer of the Bluetooth stack (which is necessary for controller emulation) with Python on Windows. It *is*, however, possible to use a KMDF profile driver to establish Interrupt/Control connections and provide hooks for Python use.

To enable NXBT use on Windows, a separate KMDF driver profile project might be necessary.

If anyone has any other ideas or experience in this area, please feel free to comment.

**Comment by DanceBot1234** [comment]
I would like to help out with windows support as well.  However, when I `pip install nxbt` on my windows 10 box I get stuck at dbus-python `error: [WinError 193] %1 is not a valid Win32 application`.  Any thoughts?  thanks

**Comment by Brikwerk** [comment]
Thanks for your interest in Windows support. At this stage, my recommendation would be to help with addressing access to the L2CAP layer of the Windows Bluetooth stack. If we can't get access to this then it's unfortunately not possible for nxbt to function.

To summarize, L2CAP is basically a low layer of the Bluetooth stack that Windows doesn't seemingly expose as easily as MacOS or Linux. Emulation of a Switch controller requires L2CAP access (among other things, check the five steps [here](https://github.com/Brikwerk/nxbt/issues/2#issuecomment-712454148) for a general list). nxbt uses it to establish a connection and communicate with the Switch.

To move this issue forward a bit more, I'll list some of my research/thoughts:
- Writing a KMDF driver is still a possibility, however, this is a bit of a last resort since the process is fairly complex. If someone has experience with writing drivers or is willing to help in this regard, please let me know!
- Use of an alternative Bluetooth stack is an option. The WIDCOMM stack seemingly supports use of the L2CAP layer through the 32.feet library.
- Finally, there's always the possibility of running a Linux virtual machine on Windows. You should be able to enable access to your Bluetooth dongle inside the VM, thus, enabling nxbt/BlueZ to emulate a controller. This isn't a native solution, so I would only recommend this if the above options prove fruitless.

Additionally, if anyone's interested in doing further research into this, try looking for projects that emulate a bluetooth keyboard on Windows (make sure it's not a Bluetooth Low Energy or BLE project). nxbt follows similar principles to keyboard emulation, so if someone is able to get a keyboard emulated, we should be able to emulate a controller.

**Comment by Brikwerk** [comment]
As of the latest release, support for Windows has been added through Vagrant-based Virtual Machines.

If someone else has other input on how native Bluetooth support could be provided, please feel free to comment and we can potentially re-open this issue to investigate further.
