### ISSUE TITLE
Test and Demo work fine, but won't connect with TUI or Webapp

### ISSUE THREAD

**Issue by Lord-Memester** [Brikwerk/nxbt#132]
I frankly have no idea what's the issue here. The only difference I noticed is the activity light on the USB Bluetooth dongle I'm using blinks and goes solid multiple times while it attempts to connect with the Test and Demo, but remains solid after one initial and uneventful blink session with TUI and Webapp.

Program is running in VirtualBox 7.0.8 with Debian 12.0.0 (amd64). Dongle in question is `Insignia` brand "Bluetooth 4.0 USB Adapter for Laptops and Desktops Compatible with Windows 10" with model number `NS-PCY5BMA2`.

**Comment by Dummydud3** [comment]
I checked out your bluetooth dongle, and its perfect. If it works fine with the Test and Demo, then it might be a compatibility issue with the rest of the script. Would you mind telling me the exact time that it blinked?

Alternatively, this could be a problem with Debian 12; i have heard in the past that people had difficulties with Debian's ping refresh rate limits, so if you want a brute force solution, you can try and install an Ubuntu branch instead.

**Comment by Lord-Memester** [comment]
> Would you mind telling me the exact time that it blinked?

I'm not exactly sure how I could be more exact. In both the test and demo scripts, the console output during connection attempts simply states when it is trying to connect and the duration for which it will attempt to do so. If there's something I'm foolishly missing here, please let me know.

> Alternatively, this could be a problem with Debian 12; i have heard in the past that people had difficulties with Debian's ping refresh rate limits, so if you want a brute force solution, you can try and install an Ubuntu branch instead.

I had many issues when I tried to run this in Ubuntu. It doesn't help that I'm very unfamiliar with the distro, and while I could try doing it again having gotten more success and practice with NXBT in Debian, it seems silly to do that when it seems to be on the path of success in Debian.

**Comment by Lord-Memester** [comment]
Update: For some unknown reason, the webapp has suddenly decided to work. I changed genuinely nothing, but I'm not looking the other way. Will update and see if the TUI works now for similarly inexplicable reasons.

**Comment by Lord-Memester** [comment]
I guess I should close the issue, given that the issue titled is no longer present.

**Comment by Dummydud3** [comment]
but you can confirm that nxbt connects to the switch successfully?

**Comment by Dummydud3** [comment]
also, the TUI is very finicky with inputs, so i would reccommend that you stick to the webapp if possible

**Comment by Lord-Memester** [comment]
> but you can confirm that nxbt connects to the switch successfully?

Yes, it does.
