### ISSUE TITLE
Macro's '#'  comments do not work

### ISSUE THREAD

**Issue by kyleyankan** [Brikwerk/nxbt#136]
I attempted to write a macro using loops. During this time I noticed the note in the docs about using the `#` character to create comments within a script. I tried this and was met with the following error, for the following script.

```
# Return to Zelda
1.0s
A 0.1s
0.5s
R L 0.2s
3.0s
A 0.2s
3.0s
```
```

Creating controller...
Waiting for connection...
Connected!
Running macro...
Controller crashed while running macro
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nxbt/controller/server.py", line 106, in run
    self.mainloop(itr, ctrl)
  File "/usr/local/lib/python3.10/dist-packages/nxbt/controller/server.py", line 155, in mainloop
    self.input.set_protocol_input(state=self.state)
  File "/usr/local/lib/python3.10/dist-packages/nxbt/controller/input.py", line 202, in set_protocol_input
    self.macro_timer_length = float(timer_length)
ValueError: could not convert string to float: 'Zeld'

```

I thought maybe it was the `Return` keyphrase, so I tried removing it, changing capitalization, etc. It always fails on the last word in a comment with the above ValueError

**Comment by Brikwerk** [comment]
How did you install NXBT? Is this the PyPi version or did you install from Github? If this was a Github install, which branch? Currently, macro comments are only supported on the Github main branch. I'm currently working on getting the PyPi version up-to-date soon here.

**Comment by kyleyankan** [comment]
> o

Hey Brikwerk, I installed from PyPi, my confusion for the versioning error. This is awesome work, thanks so much.
