### ISSUE TITLE
How to change keyboard mapping?

### ISSUE THREAD

**Issue by Ian9211** [Brikwerk/nxbt#137]
I am using Webapp to use the PC keyboard to control my NS but I am not used to the default key mapping. 
Is there a way to customize the key map?

**Comment by Ian9211** [comment]
I have solved problem by editing main.js.

**Comment by Scro-mx** [comment]
Hello, I tried to change the keyboard keys in the 2 main.js files

nxbt/nxbt/web/static/js/main.js
And
nxbt/build/lib/nxbt/web/static/js/main.js

however when I restart the Webapp, this was not taken into account (Like the Change in nxbt/nxbt/web/templates/index.html)

How can I do ?
