### ISSUE TITLE
Webapp not working

### ISSUE THREAD

**Issue by Ricca665** [Brikwerk/nxbt#147]
When typed sudo nxbt webapp it throws this:
![image](https://github.com/Brikwerk/nxbt/assets/84286914/226b1aa5-49b4-42ff-8b29-20c12df20ad6)
please fix

**Comment by strohitv** [comment]
I have this issue too.

As far as I can see, it's fixed but @Brikwerk hasn't released a new version since then, so the pip package is heavily outdated.

@Brikwerk do you have a date where the fixed version will be released for us?

**Comment by quuuut** [comment]
#121 @Ricca665 @strohitv

**Comment by Dummydud3** [comment]
This issues is already fixed, but the online pip hasnt been updated. you can still run the webapp if you clone the repo and install it locally.

**Comment by strohitv** [comment]
That's what I figured but I don't know how to do this. Is there some kind of tutorial or something on how to locally build this repo?
Sorry but I'm new to python, I don't really know this pip stuff yet..

**Comment by quuuut** [comment]
#121 finds that you have to downgrade Flask and Werkzeug to 2.0.3
`sudo pip install Werkzeug==2.0.3;sudo pip install Flask==2.0.3`

**Comment by Ricca665** [comment]
Thank you (I know I am a _tiny_ bit late)
