### ISSUE TITLE
How to hold down one button, then pressing another while still holding down the first button?

### ISSUE THREAD

**Issue by BlameFelix** [Brikwerk/nxbt#151]
Hello, I'm having trouble handling the Python Api for this specific usecase. I'm trying to hold down DPAD_DOWN and while its still held pressing x. I can't figure out how to do that. I've tried:
`nx.press_buttons(controller_index, [nxbt.Buttons.DPAD_DOWN], down=5, up=0.1, block=True)
nx.press_buttons(controller_index, [nxbt.Buttons.X], down=0.1, up=0.1, block=True)`
Which presses the second one after the first one is released.
This:
`nx.press_buttons(controller_index, [nxbt.Buttons.DPAD_DOWN], down=5, up=0.1, block=False)
nx.press_buttons(controller_index, [nxbt.Buttons.X], down=0.1, up=0.1, block=False)`
Seems to do nothing. Any Ideas?

**Comment by ghost** [comment]
How did you solve this? I'm currently making a program like this and can't figure out how to do this via any other approach other than multithreading (which didn't work for some reason).

**Comment by BlameFelix** [comment]
Hi, I hope its not too late, but maybe this will help others as well. I didn't find a way to do this in python, but with the macro syntax. For example:
```
macro = """
LOOP 10000
    DPAD_DOWN 0.5s
    DPAD_DOWN X 0.5s
    DPAD_DOWN 0.1s
    100s
"""
```
will hold down DPAD_DOWN, keep holding it, while also pressing x, and then releasing x while still holding down DPAD. I found this in one of the examples here.
