### ISSUE TITLE
sudo nxbt demo / sudo nxbt test / sudo nxbt webapp not doing anything

### ISSUE THREAD

**Issue by taffi75** [Brikwerk/nxbt#153]
![image](https://github.com/Brikwerk/nxbt/assets/75170004/74114db6-c363-4dcd-bbe4-39dd723177b3)
![image](https://github.com/Brikwerk/nxbt/assets/75170004/5d4e3ad5-4517-4f01-8add-a5c3b7a64b0f)

Everything else works fine - I've looked through issues before, and I've tried:
`sudo pip install jinja2==3.0.3 itsdangerous==2.0.1 Werkzeug==2.0.2 eventlet==0.33.0 dnspython==2.2.1` and all are installed correctly.
There is no error, nothing happens if I wait, it just immediately goes to next line. 
Installed from cloned repository, but have since tried with PyPi install (because of #29) and still didn't work...
Any help appreciated, (sorry if post is not descriptive enough, I'm new to this - just lmk what other information is needed) thanks!

**Comment by taffi75** [comment]
With more digging I'm starting to believe issues are coming from dbus, and im having all manner of problems trying to correctly install/reinstall/update it and get the nxbt.py to run standalone without giving a "No module named 'dbus'" error.

**Comment by taffi75** [comment]
Just restarted the entire process in another folder, this is no longer an issue.

**Comment by TheFinalNuke** [comment]
I'm having the same issue even after uninstalling and reinstalling. I execute `sudo nxbt demo` and all I get is "Running Demo..." on the next line without any other updates / changes
