### ISSUE TITLE
Question about multiple controllers

### ISSUE THREAD

**Issue by rugbyy** [Brikwerk/nxbt#16]
Hi,

I know this isn't the ideal place, but I wanted to ask you a question and I'm not sure how to contact you.

I know it's possible to create multiple controllers with this software. I was wondering if you can control all of those multiple created controllers using one physical controller? Is that currently possible using this software?

Basically for multiboxing.

Thanks!

**Comment by Brikwerk** [comment]
Hi @rugbyy, thanks for checking out NXBT.

Currently, the TUI and Webapp are more geared towards 1-person-per-controller situations. You could theoretically create two controllers on the same device, however, the software in the TUI/Webapp isn't really meant for orchestrating single-controller input to multiple devices. You could switch between two browser tabs but maybe this isn't ideal for your use case?

If you're handy with Python, however, this should be accomplishable through NXBT's API. You could use PyGame to get input from a single controller attached to your computer and apply it across two emulated controllers. 

Keep in mind that regardless of how you go about this, NXBT requires one Bluetooth adapter per emulated controller. So for two emulated controllers, you will need two Bluetooth adapters.

**Comment by rugbyy** [comment]
Thanks very much for your time and your reply!

You answered my question perfectly.
