### ISSUE TITLE
Systemd service override

### ISSUE THREAD

**Issue by Yamakaky** [Brikwerk/nxbt#19]
[`toggle_clean_bluez`](https://github.com/Brikwerk/nxbt/blob/v12_fix/nxbt/bluez.py#L95) overrides the `bluetooth.service` systemd file in `/lib`. It would be better to put the `ExecStart` change in `/run/systemd/system/bluetooth.service.d/nxbt.conf`. That way, reverting would be done by simply deleting this file. The change would also not survive reboots.

**Comment by Yamakaky** [comment]
As a quick and dirty change, I did the following change which works:
```py
    for i in range(0, len(lines)):
        line = lines[i]
        if line.startswith("ExecStart="):
            # If we want to ensure the plugin is enabled
            if not toggle:
                exec_start = re.sub(" --compat --noplugin=\*", "", line)
            else:
                exec_start = line + " --compat --noplugin=*"

    service = f"[Service]\nExecStart=\n{exec_start}"
    out_file_dir = "/run/systemd/system/bluetooth.service.d/"
    out_file = out_file_dir + "nxbt.conf"
    if toggle:
        os.makedirs(out_file_dir, exist_ok=True)
        with open(out_file, "w") as f:
            f.write(service)
    else:
        os.remove(out_file)
```

**Comment by Brikwerk** [comment]
I've accepted your PR to get things rolling with cleaning up the `toggle_clean_bluez` function. When I find some time, I'll see about prioritizing further cleanup (eg: removing the for loop).

Thanks again for contributing this 👍
