### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by Brikwerk** [Brikwerk/nxbt#2]
This is an issue to track MacOS support for NXBT.

Currently, MacOS provides access to the L2CAP layer (necessary for controller emulation) through the IOBluetooth Objective-C API. There are a couple of other tangentially related projects on MacOS that have leveraged this layer to emulate other peripherals. As it stands, it's possible for Python to wrap the Objective-C API and provide this functionality to NXBT.

If anyone has any other ideas or experience in this area, please feel free to comment.

**Comment by krj9cr** [comment]
I have some interest in running this on my Mac, so I poked around a bit. I'm definitely no expert, but this repo seemed useful: https://github.com/adafruit/Adafruit_Python_BluefruitLE
It's a bit outdated, but has some Bluetooth support for Linux and Mac built around BlueZ and the Objective-C API.

**Comment by Brikwerk** [comment]
Thanks for looking into this a bit more!

I've checked over the project you linked and there's certainly some interesting use of the Objective-C Bluetooth API. Unfortunately, they're not quite leveraging it in a way we could use for controller emulation. All Switch controllers communicate over Bluetooth Classic (AKA Bluetooth BR/EDR), where that library is mostly concerned with Bluetooth Low Energy. Still, definitely neat!

To move this issue forward a little bit on my part, I'll detail the problem and breakdown how I'm planning on/currently tackling the individual implementation issues. Controller emulation can largely be broken down into four steps:

1. Load the Switch Controller Service Discovery Protocol (SDP) record.
    - This is a record that lists all the properties/services of a Bluetooth device. The current SDP record used by nxbt can be found [here](https://github.com/Brikwerk/nxbt/blob/master/nxbt/controller/sdp/switch-controller.xml). In order to load an SDP record on MacOS, we need to use [this](https://developer.apple.com/documentation/iobluetooth/iobluetoothsdpservicerecord) API. The trouble with loading an SDP record on Mac is that it expects the record to be in PLIST format. PLIST files are fundamentally a little different than the XML file we've currently got. I'll need to find a way to rip the SDP record of a controller as MacOS sees it, convert the one we've got, or write a new one by hand. There's also the possibility that we could fudge emulation a little and not load the record, however, I'm fairly certain the Switch won't attempt a connection if it's not there.
2. Set the device's class to the gamepad class.
    - I haven't looked into this a ton, however, this might be another aspect we could fudge and not emulate. I don't think the Switch is too picky about this value. Worst case scenario, if this isn't possible to set through the API or command line, it's currently possible to use the Bluetooth Explorer utility to manually set this value.
3. Set discoverability/pairability.
    - Trivially accomplished through the IOBluetoothPreferences hidden API.
4. Set the device's name to a controller's name (Pro Controller, Joy-Con (L), etc).
    - Trivially accomplished with the `scutil` CLI.
5. Open L2CAP sockets on ports 17 and 19
    - I haven't looked into this much since the SDP record being loaded or not will factor into how we open the sockets. If we successfully load the record, it looks like we can simply query the record, get the prepped sockets, and be on our way.

Feel free to comment on any of the aspects I listed above or on other stuff anyone finds.

Thanks for everyone's interest!

**Comment by Brikwerk** [comment]
Quick update on some progress for this issue.

I've managed to accomplish the first 4 steps I outlined above. For 1, I ended up rewriting the SDP record by hand so that it was compatible with the plist format MacOS requires. For 2, I found that setting this value wasn't actually required for emulation, thus, I didn't end up writing any code. For 3, I used the IOBluetoothPreferences API. For 4, I used the scutil CLI to change the name of the device.

I'm currently working at getting ports to open/connect on the proper PSMs.

As a bit of visual proof:
<img width="519" alt="macos-switch-connection" src="https://user-images.githubusercontent.com/13802164/97624786-d616fa00-19e4-11eb-9579-cffcca127dd2.png">

**Comment by ilcheese2** [comment]
Are there any updates on this? Also can you share the SDP record you used?

**Comment by Brikwerk** [comment]
As of the latest release, MacOS support has been added through Vagrant-based Virtual Machines. Native support, at this point, is something I don't have the bandwidth to investigate further. Additionally, changes implemented in SwitchOS v12 and onwards have made emulation a bit more difficult (setting the device class is necessary now).

I don't have the SDP record on hand, however, I'll try to post it as a gist when I have time to search for it. In the meantime, if someone else has some suggestions or is motivated to move native support forward, we can look at re-opening this issue.
