### ISSUE TITLE
Support for SwitchOS 12.1.0

### ISSUE THREAD

**Issue by gvieralopez** [Brikwerk/nxbt#28]
I tried all solutions working for OS <12 and even the solution for 12.0.0 but none of them work in 12.1.0. If you need me to debug anything don´t hesitate to ask.

**Comment by gvieralopez** [comment]
I also get the same error but only when I try to pair using the CLI, in the web interface I only get a CRASHED message in the web.

**Comment by Brikwerk** [comment]
@gvieralopez @unsightedmetal6 Are either of you using the v12_fix branch of NXBT? If you're installing NXBT with `sudo pip3 install nxbt`, you're using the PyPi version. Unfortunately, SwitchOS v12 introduced some breaking changes that I'm working on fixing with the development version. This should hopefully release soon.

If you are using the v12_fix version, are you able to post logs from `bluetoothctl` as the Switch connects? Make sure to start `bluetoothctl` before running NXBT.

**Comment by unsightedmetal6** [comment]
> If you are using the v12_fix version, are you able to post logs from `bluetoothctl` as the Switch connects? Make sure to start `bluetoothctl` before running NXBT.

I am using that version. Here is the log from `bluetoothctl`:

myname@myname-VirtualBox:~$ bluetoothctl
Agent registered
[CHG] Controller 18:26:49:3F:4F:7F Pairable: yes
[CHG] Controller 18:26:49:3F:4F:7F Powered: no
[CHG] Controller 18:26:49:3F:4F:7F Discovering: no
[CHG] Controller 18:26:49:3F:4F:7F Class: 0x00000000
Agent unregistered
[DEL] Device B8:8A:EC:91:5C:62 Nintendo Switch
[DEL] Controller 18:26:49:3F:4F:7F Pro Controller [default]
Agent registered
[CHG] Controller 18:26:49:3F:4F:7F UUIDs: 00001801-0000-1000-8000-00805f9b34fb
[CHG] Controller 18:26:49:3F:4F:7F UUIDs: 00001800-0000-1000-8000-00805f9b34fb
[CHG] Controller 18:26:49:3F:4F:7F UUIDs: 00001108-0000-1000-8000-00805f9b34fb
[CHG] Controller 18:26:49:3F:4F:7F UUIDs: 00001200-0000-1000-8000-00805f9b34fb
[CHG] Controller 18:26:49:3F:4F:7F UUIDs: 00001112-0000-1000-8000-00805f9b34fb
[CHG] Controller 18:26:49:3F:4F:7F Powered: yes
[CHG] Controller 18:26:49:3F:4F:7F PairableTimeout: 0x00000000
[CHG] Controller 18:26:49:3F:4F:7F DiscoverableTimeout: 0x000000b4
[CHG] Controller 18:26:49:3F:4F:7F UUIDs: 00001801-0000-1000-8000-00805f9b34fb
[CHG] Controller 18:26:49:3F:4F:7F UUIDs: 00001800-0000-1000-8000-00805f9b34fb
[CHG] Controller 18:26:49:3F:4F:7F UUIDs: 00001108-0000-1000-8000-00805f9b34fb
[CHG] Controller 18:26:49:3F:4F:7F UUIDs: 00001200-0000-1000-8000-00805f9b34fb
[CHG] Controller 18:26:49:3F:4F:7F UUIDs: 00001112-0000-1000-8000-00805f9b34fb
[CHG] Controller 18:26:49:3F:4F:7F UUIDs: 00001124-0000-1000-8000-00805f9b34fb
[CHG] Controller 18:26:49:3F:4F:7F Discoverable: yes
[CHG] Controller 18:26:49:3F:4F:7F Class: 0x00002508
[CHG] Device B8:8A:EC:91:5C:62 Connected: yes
Request authorization
[agent] Accept pairing (yes/no): yes
[CHG] Device B8:8A:EC:91:5C:62 Connected: no
[CHG] Device B8:8A:EC:91:5C:62 Connected: yes
Request authorization
[agent] Accept pairing (yes/no): yes
[CHG] Device B8:8A:EC:91:5C:62 Connected: no
[bluetooth]#

The Switch only connected the second time I accepted the pairing. The controller disconnects shortly after it leaves the "Change Grip/Order" screen.

The command I am running is `sudo nxbt demo`, which tells me on the next line: `Running Demo...`. Nothing appears after that in the terminal.

Notes: I am using a Ubuntu VM on a Windows host. I am using a Python virtual environment. `sudo pip freeze` includes `nxbt==0.1.4` which appears to be the new version.

**Comment by Brikwerk** [comment]
Would you be able to uninstall/reinstall the latest development version with the following:
```
sudo pip3 uninstall nxbt
sudo pip3 install git+http://github.com/Brikwerk/nxbt.git@v12_fix
```

After that can you run `sudo nxbt test` and post the log from that here? I've pushed some changes recently that should hopefully help.

Worst case, this might be a packet timing issue caused by the VM performance penalty. Do you find NXBT or your VM sluggish? Would you also be able to post your system specs as well? Thanks 👍

**Comment by unsightedmetal6** [comment]
> Would you be able to uninstall/reinstall the latest development version with the following:
> 
> ```
> sudo pip3 uninstall nxbt
> sudo pip3 install git+http://github.com/Brikwerk/nxbt.git@v12_fix
> ```
> 
> After that can you run `sudo nxbt test` and post the log from that here? I've pushed some changes recently that should hopefully help.
> 
> Worst case, this might be a packet timing issue caused by the VM performance penalty. Do you find NXBT or your VM sluggish? Would you also be able to post your system specs as well? Thanks 👍



Upon running `sudo nxbt test`:

"[1] Attempting to initialize NXBT...
Successfully initialized NXBT.

[2] Checking for Bluetooth adapter availability...
1 Bluetooth adapter(s) available.
Adapters: ['/org/bluez/hci0'] 

[3] Please turn on your Switch and navigate to the 'Change Grip/Order menu.'
Press Enter to continue...
Creating a controller with the first Bluetooth adapter...
Successfully created a controller.

[4] Waiting for controller to connect with the Switch...
Connection timeout is 120 seconds for this test script.
Successfully connected.

[5] Attempting to exit the 'Change Grip/Order Menu'...
Controller successfully exited the menu.

All tests passed."

It did exit the menu, but then the emulated controller disappears from the Switch. I have also tried with with `sudo nxbt webapp`. That one lets me press any button I want with my keyboard, but once I exit the Change Grip/Order menu the controller disconnects.

I don't find either NXBT or my VM to be sluggish. The specs for my Windows host are:

>Windows 10 Home
>Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz
>16 GB RAM
>Intel UHD Graphics 630 along with a GeForce RTX 2060
>It is a laptop
