### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by 1575788715** [Brikwerk/nxbt#30]
Hello, I used your latest nxbt0.1.4. My switch is 12.1.0. I still can't connect to my switch. I use VM
![image](https://user-images.githubusercontent.com/33148522/133222354-f8d3b054-aec4-4aab-b067-a37ca23ea711.png)
It didn't respond

**Comment by Brikwerk** [comment]
@FireBro234 SwitchOS v13.1.0 doesn't introduce any breaking changes from my testing. I'm not able to produce connection issues when using NXBT and v13.1.0 on several different systems (Linux/Mac/Windows). This might come down to a hardware-specific issue. What are your system specs and how are you connecting to the Switch (eg: Windows with a VM)? Did you have the "Change Grip/Order Menu" open when you were connecting? Lastly, can you run `sudo bluetoothctl`, then run `sudo nxbt test`, wait for the test to complete and paste the output from `bluetoothctl`?

**Comment by FireBro234** [comment]
> @FireBro234 SwitchOS v13.1.0 doesn't introduce any breaking changes from my testing. I'm not able to produce connection issues when using NXBT and v13.1.0 on several different systems (Linux/Mac/Windows). This might come down to a hardware-specific issue. What are your system specs and how are you connecting to the Switch (eg: Windows with a VM)? Did you have the "Change Grip/Order Menu" open when you were connecting? Lastly, can you run `sudo bluetoothctl`, then run `sudo nxbt test`, wait for the test to complete and paste the output from `bluetoothctl`?

Wait a minute, the issue that 1575788715 is having is that the bluetooth adapter is below 4.1, so the issue that i had is that my USB bluetooth dongle's version is 2.0 so i switched to internal bluetooth dongle which version is 5.2 and it worked! 😱 

https://user-images.githubusercontent.com/93390289/139485802-23ebd84c-072c-4ef9-bfee-8adda7c42365.mp4

**Comment by Brikwerk** [comment]
@FireBro234 Glad to hear you were able to get things sorted.

Since Firebro's problem was solved, I'm going to close this issue for now.

@1575788715 If connection issues persist, feel free to reopen the issue.
