### ISSUE TITLE
Unable to connect via API, WEBAPP works

### ISSUE THREAD

**Issue by Koobold** [Brikwerk/nxbt#33]
Hey, the title says it, i can connect to the switch via Webapp function, but there ist no success when i use the function with python, as you wrote in your manual.

Can you help me?

**Comment by Brikwerk** [comment]
Can you provide a minimum viable example of the code that you're using, the output from this code, and the output of `sudo nxbt test`? What state is your Switch in when you attempt to connect with your code?

**Comment by Koobold** [comment]
pi@raspberrypi:~/Desktop $ sudo nxbt test
[1] Attempting to initialize NXBT...
Successfully initialized NXBT.

[2] Checking for Bluetooth adapter availability...
1 Bluetooth adapter(s) available.
Adapters: ['/org/bluez/hci0'] 

[3] Please turn on your Switch and navigate to the 'Change Grip/Order menu.'
Press Enter to continue...
Creating a controller with the first Bluetooth adapter...
Successfully created a controller.

[4] Waiting for controller to connect with the Switch...
Connection timeout is 120 seconds for this test script.
Successfully connected.

[5] Attempting to exit the 'Change Grip/Order Menu'...
Controller successfully exited the menu.

All tests passed.
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/util.py", line 265, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.7/multiprocessing/util.py", line 189, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 861, in _decref
    tls.connection.close()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 175, in close
    if self._handle is not None:
TypeError: <lambda>() takes 1 positional argument but 2 were given

**Comment by Koobold** [comment]
In the test, the switch does show an other controller-colour, is this normal? it was green. when i use the WEBAPP the, it was gray, sometimes in the API, also gray.

**Comment by Brikwerk** [comment]
The test seems to be running alright, which means the API should be functional. Could you please post a minimum example from your code that causes issues?

For your question, controller colour doesn't matter. The test code is just a little more flamboyant than the webapp (or the API) and uses a random colour each time it runs.

**Comment by Koobold** [comment]
Thanks, now i have a solution.

eingabe = input("Connect: new(1) reconnect(2): ")
if eingabe == "1":
    # Create a Pro Controller and wait for it to connect
    controller_index = nx.create_controller(nxbt.PRO_CONTROLLER)
    print("1")
    time.sleep(3)
    print("2")
    nx.wait_for_connection(controller_index)
    print("Connected")
if eingabe == "2":
    # Get a list of all previously connected Switches and pass it as a reconnect_address argument
    controller_index = nx.create_controller(
        nxbt.PRO_CONTROLLER,
        reconnect_address=nx.get_switch_addresses())
    print("1")
    nx.wait_for_connection(controller_index)
    print("Connected")

**Comment by Brikwerk** [comment]
For the above code, the only thing I would note is that you need to exit the "Change Grip/Order" menu with the emulated controller (or with another controller while the emulated one is connected) before it can be reconnected to a Switch. 

I'm also not really sure what problems you were encountering to begin with, however, I gave your code a run on my Raspberry Pi (without the extra sleep) and it appears to be functioning correctly?

Anyways, it seems that things are working for you, so I'll close this issue for now. Feel free to re-open if you had any other questions/comments pertaining to this issue.
