### ISSUE TITLE
Webapp 'Escape' Error: Windows 10

### ISSUE THREAD

**Issue by SHZyontz** [Brikwerk/nxbt#99]
I'm trying to use the webapp on Windows 10, but it doesn't seem to work. I get the following error (which seems standard), but I do not have the path usr/local/bin/nxbt OR usr/local/lib/python3.8/ anywhere I can see. Does anyone know how to fix this for Windows, I've tried some fixes but that seems like they only work on linux.

Traceback (most recent call last):
  File "/usr/local/bin/nxbt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/nxbt/cli.py", line 321, in main
    from .web import start_web_app
  File "/usr/local/lib/python3.8/dist-packages/nxbt/web/__init__.py", line 1, in <module>
    from .app import start_web_app
  File "/usr/local/lib/python3.8/dist-packages/nxbt/web/app.py", line 9, in <module>
    from flask import Flask, render_template, request
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py)

**Comment by YiZhiRikka** [comment]
Consult #75 .
Run `sudo pip install jinja2==3.0.3`
Maybe you will run into other problems.

```
cannot import name 'json' from 'itsdangerous'
```
try `sudo pip install itsdangerous==2.0.1`

```
cannot import name 'BaseResponse' from 'werkzeug.wrappers'
```
try `sudo pip install Werkzeug==2.0.2`

```
cannot set 'is_timeout' attribute of immutable type 'TimeoutError'
```
try ` sudo pip install eventlet==0.33.0 dnspython==2.2.1`

or you can use a line instead.
`sudo pip install jinja2==3.0.3 itsdangerous==2.0.1 Werkzeug==2.0.2 eventlet==0.33.0 dnspython==2.2.1`

**Comment by YiZhiRikka** [comment]
Nxbt only work on linux. You can use virtual machine such as VirtualBox.
